---
- name: add nodejs from Nodesource
  become: true
  shell: |
    get_url -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: upgrade all packages
  become: true
  apt:
    upgrade: "yes"

- name: install nodejs
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install n
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
